version: '3.3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: php:latest-apache
    container_name: tubes-1
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 8008:80
  db:
    container_name: tubes-1-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: sepotipayi
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./sepotipayi.sql:/docker-entrypoint-initdb.d/sepotipayi.sql:ro
    ports:
      - 6666:3306
  phpmyadmin:
    container_name: tubes-1-phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 64M
    ports:
      - 8888:80

